exastro-suite/it-automation2-test

.gitignore, ita_root/common_library/common/__init__.py, ita_root/common_library/common/dbconnect.py, ita_root/common_library/common/logger.py, ita_root/ita_api_organization/.gitignore, ita_root/ita_api_organization/logging.yml
・DB接続モジュール
・ログ出力モジュール
・その他環境設定関連
=> common_library.common関係

.devcontainer/docker-compose.yml, .gitignore, ita_root/common_libs/common/logger.py, ita_root/ita_api_organization/.env.sample, ita_root/ita_api_organization/Dockerfile, ita_root/ita_api_organization/api.py, ita_root/ita_api_organization/logging.yml
コンテナ修正
・PYTHONPATHの追加
・pipの最新化とdotenvモジュールの追加
ログ関連
・ログインスタンスのネームスペースの修正
・ログ出力の、ファイル出力への切替設定ファイルのサンプル
環境まわり
・api.pyで、環境ファイルの読み込みと、ログインスタンスの生成
・無視リストの追加
=> コンテナ修正、ログ関連、環境まわりの修正

ita_root/common_libs/common/__init__.py, ita_root/common_libs/common/dbconnect.py
organization用DBと、workspace用DBへの接続クラスを分ける
=> DB接続クラスの修正

ita_root/common_libs/common/__init__.py, ita_root/common_libs/common/dbconnect/dbconnect_common.py, ita_root/common_libs/common/dbconnect/dbconnect_org.py, ita_root/common_libs/common/dbconnect/dbconnect_ws.py, ita_root/ita_api_admin/controllers/organization_create_controller.py, ita_root/ita_api_admin/controllers/workspace_create_controller.py, ita_root/ita_api_admin/libs/api_common.py, ita_root/ita_api_admin/sql/ita_common.sql, ita_root/ita_api_admin/sql/organization.sql, ita_root/ita_api_organization/libs/api_common.py
DB周り
・DB名はuuidで発行
・パスワードは暗号化
organizationがURLに入る（ita-adminのみ）
リクエストのパラメータヴァリデーション回り
APIフィルター
=> DB周りとその他修正

ita_root/common_libs/common/logger.py, ita_root/ita_api_admin/libs/admin_common.py, ita_root/ita_api_organization/libs/organization_common.py
=> ・ヘッダーのROLESをリスト型で保存

ita_root/common_libs/api/api_common.py, ita_root/ita_api_admin/libs/admin_common.py, ita_root/ita_api_organization/libs/organization_common.py
デフォルト言語の設定が重複していたので削除
権限チェックは１を優先した値のみ返す
=> APIの成功時は必ずdata属性を付与する

ita_root/common_libs/common/dbconnect/dbconnect_common.py, ita_root/common_libs/common/dbconnect/dbconnect_org.py, ita_root/common_libs/common/logger.py
=> ユーザのログレベルをシステム設定から取得

ita_root/common_libs/column/column_class.py, ita_root/common_libs/column/id_class.py, ita_root/common_libs/loadtable/load_table.py, ita_root/common_libs/validate/valid_xxxxx-1001.py
loadtable関連
個別処理の仮構成
メニュー作成相当（仮）のfilter maintenance対応
=> loadtable関連 validate filter maintenance

ita_root/ita_api_organization/openapi.yaml, ita_root/ita_api_organization/swagger/swagger.yaml
=> swagger conductor関連

ita_root/common_libs/conductor/functions/utils.py
chk_format
chk_connected_nodes
chk_conductor
chk_edge
=> common_libs.conductor.functions.util

ita_root/common_libs/loadtable/load_table.py
=> loadtable 修正

ita_root/common_libs/column/file_upload_class.py, ita_root/common_libs/column/file_upload_encrypt_class.py, ita_root/common_libs/common/util.py, ita_root/common_libs/loadtable/load_table.py
ファイルアップロードカラムのファイル配置処理修正
＋util.pyの以下修正。
byte書き込みに変更。＋引数が文字列ならdecodeして、byte変換
upload_file
encrypt_upload_file
=> fileupload loadtable　修正

ita_root/common_libs/loadtable/load_table.py
loadtable 廃止時の処理修正
個別処理時の try except　仮対応
=> loadtable 廃止時の処理修正

ita_root/common_libs/loadtable/load_table.py, ita_root/common_libs/validate/valid_10704.py
loadtable  exec_maintenance PK指定のオプション追加
=> loadtable conductor 修正

manifest_template/ita-mariadb.yaml
ita-mariadb.yaml に subPath を追加、priviliged : false にしました。
よろしくお願いいたします。
=> added subPath, changed value of Priviliedged into false

ita_root/common_libs/loadtable/load_table.py
=> loadtable jnl無し対応、msg、復活備考のみ

ita_root/common_libs/column/last_update_user_class.py, ita_root/ita_api_organization/controllers/conductor_controll_controller.py, ita_root/ita_api_organization/libs/conductor_controll.py
=> conductor rest権限修正 last_update_user修正　

ita_root/ita_api_organization/Dockerfile
=> dictknife追加

ita_root/ita_by_ansible_legacy_role_vars_listup/backyard_libs/ansible_driver/classes/DeviceTableClass.py, ita_root/ita_by_ansible_legacy_role_vars_listup/backyard_libs/ansible_driver/classes/ExpandableElementClass.py, ita_root/ita_by_ansible_legacy_role_vars_listup/backyard_libs/ansible_driver/classes/MemberColCombElementClass.py, ita_root/ita_by_ansible_legacy_role_vars_listup/backyard_libs/ansible_driver/classes/MovementMaterialLinkTableClass.py, ita_root/ita_by_ansible_legacy_role_vars_listup/backyard_libs/ansible_driver/classes/MovementTableClass.py, ita_root/ita_by_ansible_legacy_role_vars_listup/backyard_libs/ansible_driver/classes/MovementVarsLinkTableClass.py, ita_root/ita_by_ansible_legacy_role_vars_listup/backyard_libs/ansible_driver/classes/NestVarsMemberColCombTableClass.py, ita_root/ita_by_ansible_legacy_role_vars_listup/backyard_libs/ansible_driver/classes/NestVarsMemberMaxColTableClass.py, ita_root/ita_by_ansible_legacy_role_vars_listup/backyard_libs/ansible_driver/classes/NestVarsMemberTableClass.py, ita_root/ita_by_ansible_legacy_role_vars_listup/backyard_libs/ansible_driver/classes/NonExpandableElementClass.py, ita_root/ita_by_ansible_legacy_role_vars_listup/backyard_libs/ansible_driver/classes/RoleNameTableClass.py, ita_root/ita_by_ansible_legacy_role_vars_listup/backyard_libs/ansible_driver/classes/RolePkgTableClass.py, ita_root/ita_by_ansible_legacy_role_vars_listup/backyard_libs/ansible_driver/classes/TableBaseClass.py, ita_root/ita_by_ansible_legacy_role_vars_listup/backyard_libs/ansible_driver/classes/TemplateTableClass.py, ita_root/ita_by_ansible_legacy_role_vars_listup/backyard_libs/ansible_driver/classes/VariableClass.py, ita_root/ita_by_ansible_legacy_role_vars_listup/backyard_libs/ansible_driver/functions/util.py
DeviceTableClass.py の変更のみ
他の変更点はlint系の修正です
=> 機器一覧classの変数定義漏れ

ita_root/ita_api_organization/libs/menu_excel.py
=> JsonColumn対応

ita_root/common_libs/conductor/classes/exec_util.py
=> conductor 修正

ita_root/common_libs/ansible_driver/classes/controll_ansible_agent.py, ita_root/ita_by_ansible_execute/backyard_main.py, ita_root/ita_by_ansible_execute/templates/docker-compose.yml
=> system pruneはしない

ita_root/common_libs/column/column_class.py, ita_root/common_libs/loadtable/load_table.py
msg引数：MSG-0002：
組み合わせ一意の対象:組み合わせの対象の廃止を除外
復活時の処理:バリデーション追加
=> msg引数,組み合わせ一意の対象,復活時の処理 修正
